import { jsPDF } from 'jspdf';

const formatDate = (value) => {
  if (!value) return 'N/A';

  return new Date(value).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

const drawRow = (doc, rowValues, columnWidths, startX, y, lineHeight) => {
  let x = startX;
  rowValues.forEach((value, index) => {
    doc.text(String(value), x, y);
    x += columnWidths[index];
  });

  return y + lineHeight;
};

export function downloadDashboardReport({
  fileName,
  title,
  generatedBy,
  summaryRows = [],
  tableHeaders = [],
  tableRows = []
}) {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const lineHeight = 8;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  doc.setFontSize(18);
  doc.text(title, margin, y);
  y += 10;

  doc.setFontSize(11);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 7;
  doc.text(`Generated by: ${generatedBy || 'System'}`, margin, y);
  y += 12;

  doc.setFontSize(13);
  doc.text('Summary', margin, y);
  y += 8;

  doc.setFontSize(11);
  summaryRows.forEach(([label, value]) => {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = 20;
    }

    doc.text(`${label}: ${value}`, margin, y);
    y += 7;
  });

  y += 4;
  if (y > pageHeight - margin) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(13);
  doc.text('Election Details', margin, y);
  y += 8;

  if (tableHeaders.length === 0) {
    doc.setFontSize(11);
    doc.text('No data available.', margin, y);
    doc.save(fileName || 'dashboard-report.pdf');
    return;
  }

  const columnWidths = tableHeaders.map(() => contentWidth / tableHeaders.length);
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  y = drawRow(doc, tableHeaders, columnWidths, margin, y, lineHeight);
  doc.setFont(undefined, 'normal');

  tableRows.forEach((row) => {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = 20;
      doc.setFont(undefined, 'bold');
      y = drawRow(doc, tableHeaders, columnWidths, margin, y, lineHeight);
      doc.setFont(undefined, 'normal');
    }

    const normalizedRow = row.map((value) => {
      if (value === null || value === undefined || value === '') return 'N/A';
      return String(value).length > 24 ? `${String(value).slice(0, 21)}...` : String(value);
    });

    y = drawRow(doc, normalizedRow, columnWidths, margin, y, lineHeight);
  });

  doc.save(fileName || 'dashboard-report.pdf');
}

export { formatDate };